config/routes.rb
Rails.application.routes.draw do

  root 'root_pages#root'

  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :boards, only: [:create, :update, :destroy, :show, :index]
    resources :lists, only: [:create, :update, :destroy, :show, :index]
    resources :cards, only: [:create, :update, :destroy, :show, :index]
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :lists
end

app/models/board_member.rb
class BoardMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :list
  has_many :todo_items
  has_many :card_assignments
  has_many :users, through: :card_assignments
end

app/models/card_assignment.rb
class CardAssignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :card
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :board
  has_many :cards
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :card
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :boards
  has_many :card_assignments
  has_many :cards, through: :card_assignments

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user && user.is_password?(password)
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(@password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64
  end

  def new_session_token
    @session_token = generate_session_token
    save!
    session_token
  end

end

app/controllers/api/boards_controller.rb
class Api::BoardsController < ApplicationController
  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      render json: @board
    else
      render json: @board.errors.full_messages, status: :unprocessable_entity
    end
  end

  def index
    @boards = Board.all
    render json: @boards
  end

  def show
    @board = Board.find(params[:id])
    render 'show'
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(board_params)
      render json: @board
    else
      render json: @board.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    board = Board.find(params[:id])
    board.destroy
    render json: board
  end

  private
  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/api/cards_controller.rb
class Api::CardsController < ApplicationController
  def create
    @card = Card.new(card_params)
    if @card.save
      render json: @card
    else
      render json: @card.errors.full_messages, status: :unprocessable_entity
    end
  end

  def index
    @cards = Card.all
    render json: @cards
  end

  def show
    @card = Card.find(params[:id])
    render json: @card
  end

  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      render json: @card
    else
      render json: @card.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    card = Card.find(params[:id])
    card.destroy
    render json: card
  end


  private
  def card_params
    params.require(:card).permit(:title, :description, :ord, :list_id)
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController
  def create
    @list = List.new(list_params)
    if @list.save
      render json: @list
    else
      render json: @list.errors.full_messages, status: :unprocessable_entity
    end
  end

  def index
    @lists = List.all
    render json: @lists
  end

  def show
    @list = List.find(params[:id])
    render json: @list
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      render json: @list
    else
      render json: @list.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    render json: list
  end

  private
  def list_params
    params.require(:list).permit(:title, :ord, :board_id)
  end
end

app/controllers/api/todo_items_controller.rb
class Api::CardsController < ApplicationController
  private
  def card_params
    params.require(:card).permit(:title, :done, :card_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(
      session[:session_token]
    )
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.new_session_token
  end

  def logout
    current_user.new_session_token
    session[:session_token] = nil
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/root_pages_controller.rb
class RootPagesController < ApplicationController
  before_action :check_login

  def root
  end

  private

  def check_login
    redirect_to new_session_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )
    if @user
      login(@user)
      redirect_to 'root'
    else
      flash.now["errors"] = "Invalid Username or Password"
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to root_url
    else
      flash.now["errors"] = @user.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = <<-HTML
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
    HTML

    html.html_safe
  end
end

app/helpers/root_pages_helper.rb
module RootPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trello</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/root_pages/root.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TRELLO</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Index</a></li>
        <li><a href="#/boards/new">New Board</a></li>
        <li><%= button_to "Sign Out", session_url, method: :delete %></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="content">

</div>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="username">Username</label>
  <input type="text"
         id="username"
         name="user[username]">
  <label for="password">Password</label>
  <input type="password"
          id="password"
          name="user[password]">
  <input type="submit" value="Sign Up">
</form>